# Generated by Django 2.1.12 on 2019-10-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('djangocms_blog', '0037_auto_20190806_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='access groups'),
        ),
    ]
