# Generated by Django 3.1.6 on 2021-10-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0039_auto_20200331_2227'),
        ('djangocms_blog', '0039_auto_20200102_1356'),
    ]

    operations = [
    ]
