# Generated by Django 2.1.12 on 2020-01-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0038_post_media'),
        ('djangocms_blog', '0039_auto_20200102_1356'),
    ]

    operations = [
    ]
